---
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    reviewers:
      - zchee
    labels:
      - dependabot
      - dependencies

  - package-ecosystem: gomod
    directory: /tools
    open-pull-requests-limit: 50
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    reviewers:
      - zchee
    labels:
      - dependabot
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "gha"
    open-pull-requests-limit: 20
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    reviewers:
      - zchee
    labels:
      - dependabot
      - dependencies

enable-beta-ecosystems: true
